"""make user_id nullable

Revision ID: af1b796c1e10
Revises: 345fa90b2c29
Create Date: 2025-04-28 03:00:10.416248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af1b796c1e10'
down_revision = '345fa90b2c29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emailverificationtoken', 'user_id',
                   existing_type=mysql.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emailverificationtoken', 'user_id',
                   existing_type=mysql.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###